[package]
name = "mock-example"
version = "0.1.0"
authors = ["pavver <pavvers1@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0"
AS5600-Driver = { version = "0.1.0", features = ["mock", "std", "anyhow"] }
